BuildingManager.Web/Controllers/AuthController.cs
using System.Threading.Tasks;
using BuildingManager.Business.Dtos;
using BuildingManager.Entities.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BuildingManager.Web.Controllers
{
    public class AuthController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;
        public AuthController( UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Login(string ReturnUrl = null)
        {
            return View(new LoginDto()
            {
                ReturnUrl = ReturnUrl
            });
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await _userManager.FindByEmailAsync(model.Email);
            if (user == null) return View(model);
            var result = await _signInManager.PasswordSignInAsync(user,model.Password,true,false);
            if (result.Succeeded) return Redirect(model.ReturnUrl ?? "~/");
            return View(model);
        }
        
        
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return Redirect("~/");
        }
    }
}

BuildingManager.Web/Controllers/ExpenseController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using BuildingManager.Business.Abstract;
using BuildingManager.Business.Dtos;
using BuildingManager.Web.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace BuildingManager.Web.Controllers
{
    [AuthorizeByRole(Roles="Admin")]
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly IExpenseTypeService _expenseTypeService;
        private readonly IFlatService _flatService;

        public ExpenseController(IExpenseService expenseService, IExpenseTypeService expenseTypeService, IFlatService flatService)
        {
            _expenseService = expenseService;
            _expenseTypeService = expenseTypeService;
            _flatService = flatService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var expenses = await _expenseService.GetExpensesWithRelations();
            return View(expenses.Data);
        }

        [HttpGet]
        public async Task<IActionResult> GetDebtOfExpense()
        {
            var expenses = await _expenseService.GetExpensesWithRelations();
            var expensesOfDebt = expenses.Data.Where(e=>e.IsPaid==false).ToList();
            return View(expensesOfDebt);
        }
        
        [HttpGet]
        public async Task<IActionResult> GetPaidExpense()
        {
            var expenses = await _expenseService.GetExpensesWithRelations();
            var paidExpenses = expenses.Data.Where(e=>e.IsPaid==true).ToList();
            return View(paidExpenses);
        }
        
        [HttpGet]
        public IActionResult DeleteExpense(int id)
        {
            _expenseService.Remove(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddExpense()
        {
            var expenseTypes = await _expenseTypeService.GetAllAsync();
            var flats = await _flatService.GetAllAsync();
            var createExpense = new CreateExpenseDto
            {
                ExpenseTypes = expenseTypes.Data,
                Flats = flats.Data
            };
            return View(createExpense);
        }

        [HttpPost]
        public async Task<IActionResult> AddExpense(CreateExpenseDto createExpenseDto)
        {
            if (!ModelState.IsValid)
            {
                return View(createExpenseDto);
            }
            createExpenseDto.InvoiceDate = DateTime.Now;
            createExpenseDto.IsPaid = false;
            await _expenseService.AddAsync(createExpenseDto);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddExpenseMultiple()
        {
            var expenseTypes =await _expenseTypeService.GetAllAsync();
            var flats = await _flatService.GetAllAsync();
            var createExpense = new CreateExpenseDto
            {
                ExpenseTypes = expenseTypes.Data,
                Flats = flats.Data
            };
            return View(createExpense);
        }
        
        [HttpPost]
        public async Task<IActionResult> AddExpenseMultiple(CreateExpenseDto expenses)
        {
            if (!ModelState.IsValid)
            {
                return View(expenses);
            }
            await _expenseService.AddDebtMultiple(expenses);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateExpense(int id)
        {
            var expense = await _expenseService.GetByIdAsync(id);
            var expenseTypes = await _expenseTypeService.GetAllAsync();
            var flats = await _flatService.GetAllAsync();
            var expenseToUpdate = new UpdateExpenseDto()
            {
                Id = expense.Data.Id,
                IsPaid = expense.Data.IsPaid,
                Price = expense.Data.Price,
                InvoiceDate = DateTime.Now,
                ExpenseTypes = expenseTypes.Data,
                Flats = flats.Data
            };
            return View(expenseToUpdate);
        }
        
        [HttpPost]
        public IActionResult UpdateExpense(UpdateExpenseDto updateExpenseDto)
        {
            if (!ModelState.IsValid)
            {
                return View(updateExpenseDto);
            }
            _expenseService.Update(updateExpenseDto);
            return RedirectToAction("Index");
        }
  
     
    }
}

BuildingManager.Web/Controllers/FlatController.cs
using System.Threading.Tasks;
using BuildingManager.Business.Abstract;
using BuildingManager.Business.Dtos;
using Microsoft.AspNetCore.Mvc;
using BuildingManager.Web.Extensions;

namespace BuildingManager.Web.Controllers
{
    [AuthorizeByRole(Roles="Admin")]
    public class FlatController : Controller
    {
        private IFlatService _flatService;
        private IBuildingService _buildingService;
        private IUserService _userService;

        public FlatController(IFlatService flatService, IBuildingService buildingService, IUserService userService)
        {
            _flatService = flatService;
            _buildingService = buildingService;
            _userService = userService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var flats = await _flatService.GetAllFlatsByRelations();
            return View(flats.Data);
        }

        [HttpGet]
        public IActionResult DeleteFlat(int id)
        {
            _flatService.Remove(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddFlat()
        {
            var buildingDto = await _buildingService.GetAllAsync();
            var userDto = await _userService.GetAllAsync();
            var flatCreateDto = new FlatCreateDto()
            {
                Buildings = buildingDto.Data,
                Users =  userDto.Data
            };
            return View(flatCreateDto);
        }

        [HttpPost]
        public async Task<IActionResult> AddFlat(FlatCreateDto flatCreateDto)
        {
            if (!ModelState.IsValid)
            {
                return View(flatCreateDto);
            }
            await _flatService.AddAsync(flatCreateDto);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateFlat(int id)
        {
            var flat = await _flatService.GetByIdAsync(id);
            var buildingDto = await _buildingService.GetAllAsync();
            var userDto = await _userService.GetAllAsync();
            var flatUpdateDto = new FlatUpdateDto()
            {
                Id = flat.Data.Id,
                FlatNumber = flat.Data.FlatNumber,
                IsEmpty = flat.Data.IsEmpty,
                TypeOfFlat = flat.Data.TypeOfFlat,
                Building = buildingDto.Data,
                Users = userDto.Data
            };
            return View(flatUpdateDto);
        }

        [HttpPost]
        public IActionResult UpdateFlat(FlatUpdateDto flatUpdateDto)
        {
            if (!ModelState.IsValid)
            {
                return View(flatUpdateDto);
            }
            _flatService.Update(flatUpdateDto);
            return RedirectToAction("Index");
        }
        
    }
}

BuildingManager.Web/Controllers/MessageController.cs
using System.Linq;
using System.Threading.Tasks;
using BuildingManager.Business.Abstract;
using BuildingManager.Business.Dtos;
using BuildingManager.Web.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace BuildingManager.Web.Controllers
{
    [AuthorizeByRole(Roles="Admin")]
    public class MessageController : Controller
    {
        private IMessageService _messageService;
        private IUserService _userService;

        public MessageController(IMessageService messageService, IUserService userService)
        {
            _messageService = messageService;
            _userService = userService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Inbox()
        {
           var user = _userService.GetUserFromSession();
           var allMessages = await _messageService.GetAllAsync();
           if (allMessages.Data != null)
           {
               var messageList = allMessages.Data.Where(m=>m.ReceiverEmail == user.Email).ToList(); 
               return View(messageList);
           }
           return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> Outbox()
        {
            var user = _userService.GetUserFromSession();
            var allMessages = await _messageService.GetAllAsync();
            if (allMessages.Data != null)
            {
                var messageList = allMessages.Data.Where(m=>m.SenderEmail == user.Email).ToList(); 
                return View(messageList);
            }
            return View();
        }
        
        [HttpGet]
        public IActionResult SendMessage()
        {
            return View();
        }
       
        [HttpPost]
        public async Task<IActionResult> SendMessage(MessageDto message)
        {
            var user = _userService.GetUserFromSession();
            message.SenderEmail = user.Email;
            await _messageService.AddAsync(message);
            return RedirectToAction("OutBox");
        }
        
        [HttpGet]
        public IActionResult DeleteMessageFromInbox(int id)
        {
            _messageService.Remove(id);
            return RedirectToAction("Inbox");
        }
        
        [HttpGet]
        public IActionResult DeleteMessageFromOutbox(int id)
        {
            _messageService.Remove(id);
            return RedirectToAction("Outbox");
        }
    }
}

BuildingManager.Web/Views/Shared/_Footer.cshtml
 <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
 </footer>

BuildingManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Building Manager | Doğukan Muhittin Gümüş </title>

    @await Html.PartialAsync("_Styles")
    @RenderSection("Styles",false)
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <!-- sidebar menu -->
            @if (User.IsInRole("Admin"))
            {
              @await Html.PartialAsync("_SideBar")
            } else if (User.IsInRole("User"))
            {
              @await Html.PartialAsync("_UserSideBar")
            }
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        @await Html.PartialAsync("_TopNavigation")
        <!-- /top navigation -->

      <!-- page content -->
      <div class="right_col" role="main">
        <div class="row">
          <div class="col-md-12">
            <div class="container">
              @RenderBody()
            </div>
          </div>
        </div>
        </div>
         
        <!-- /page content -->

        <!-- footer content -->
       @await Html.PartialAsync("_Footer")
        <!-- /footer content -->
      </div>
    </div>

    @await Html.PartialAsync("_Scripts")
	  @RenderSection("Scripts",false)
  </body>
</html>

BuildingManager.Web/Views/Shared/_Scripts.cshtml
<!-- jQuery -->
<script src="~/vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<!-- FastClick -->
<script src="~/vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="~/vendors/nprogress/nprogress.js"></script>
<!-- Chart.js -->
<script src="~/vendors/Chart.js/dist/Chart.min.js"></script>
<!-- gauge.js -->
<script src="~/vendors/gauge.js/dist/gauge.min.js"></script>
<!-- bootstrap-progressbar -->
<script src="~/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<!-- iCheck -->
<script src="~/vendors/iCheck/icheck.min.js"></script>
<!-- Skycons -->
<script src="~/vendors/skycons/skycons.js"></script>
<!-- Flot -->
<script src="~/vendors/Flot/jquery.flot.js"></script>
<script src="~/vendors/Flot/jquery.flot.pie.js"></script>
<script src="~/vendors/Flot/jquery.flot.time.js"></script>
<script src="~/vendors/Flot/jquery.flot.stack.js"></script>
<script src="~/vendors/Flot/jquery.flot.resize.js"></script>
<!-- Flot plugins -->
<script src="~/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="~/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
<script src="~/vendors/flot.curvedlines/curvedLines.js"></script>
<!-- DateJS -->
<script src="~/vendors/DateJS/build/date.js"></script>
<!-- JQVMap -->
<script src="~/vendors/jqvmap/dist/jquery.vmap.js"></script>
<script src="~/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
<script src="~/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="~/vendors/moment/min/moment.min.js"></script>
<script src="~/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- Custom Theme Scripts -->
<script src="~/build/js/custom.min.js"></script>
<script src="~/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
     <script src="~/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
     <script src="~/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
     <script src="~/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
     <script src="~/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
     <script src="~/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
     <script src="~/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
     <script src="~/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
     <script src="~/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
     <script src="~/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
     <script src="~/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
     <script src="~/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
     <script src="~/vendors/jszip/dist/jszip.min.js"></script>
     <script src="~/vendors/pdfmake/build/pdfmake.min.js"></script>
     <script src="~/vendors/pdfmake/build/vfs_fonts.js"></script>

BuildingManager.Web/Views/Shared/_SideBar.cshtml
   <div class="navbar nav_title" style="border: 0;">
                <a href="#" class="site_title"><span>Building Manager</span></a>
              </div>
  
              <div class="clearfix"></div>
  
              <!-- menu profile quick info -->
   <div class="profile clearfix">
     <div class="profile_pic">
       <img src="~/images/img.jpg" alt="..." class="img-circle profile_img">
     </div>
     <div class="profile_info">
       @if (User.Identity.IsAuthenticated)
       {
         <span>Hoşgeldiniz</span>
         <h2>@User.Identity.Name</h2>
       }
     </div>
   </div>
              <!-- /menu profile quick info -->
   <br />
  
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <ul class="nav side-menu">
              <li><a asp-controller="Announcement" asp-action="Index"><i class="fa fa-bullhorn"></i>Duyurular</a></li>
              <li><a><i class="fa fa-building"></i> Site <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a asp-controller="Building" asp-action="Index"><i class="fa fa-building"></i>Bloklar</a></li>
                      <li><a asp-controller="Flat" asp-action="Index"><i class="fa fa-home"></i>Daireler</a></li>
                    </ul>
              </li>
           <li><a><i class="fa fa-envelope"></i> Mesajlar <span class="fa fa-chevron-down"></span></a>
           <ul class="nav child_menu">
             <li><a asp-controller="Message" asp-action="Inbox"><i class="fa fa-inbox"></i>Gelen Kutusu</a></li>
             <li><a asp-controller="Message" asp-action="Outbox"><i class="fa fa-arrow-right"></i>Giden Kutusu</a></li>
             <li><a asp-controller="Message" asp-action="SendMessage"><i class="fa fa-comments"></i>Mesaj Gönder</a></li>
           </ul>
           <li><a asp-controller="User" asp-action="Index"><i class="fa fa-user"></i>Kullanıcılar</a></li>
                  
                  <li><a><i class="fa fa-cc-visa"></i> Finans <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                       <li><a asp-controller="ExpenseType" asp-action="Index"><i class="fa fa-shopping-cart"></i>Gider Tipleri</a></li>
                       <li><a asp-controller="Expense" asp-action="Index"><i class="fa fa-money"></i>Giderler</a></li>
                       <li><a asp-controller="Expense" asp-action="GetDebtOfExpense"><i class="fa fa-ban"></i>Borç Listesi</a></li>
                       <li><a asp-controller="Expense" asp-action="GetPaidExpense"><i class="fa fa-check-circle"></i>Ödenenler Listesi</a></li>
                    </ul>
                   </li>
                  </ul> 
        </div>

  </div>

BuildingManager.Web/Views/Shared/_Styles.cshtml
 <!-- Bootstrap -->
    <link href="~/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
	
    <!-- bootstrap-progressbar -->
    <link href="~/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="~/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="~/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="~/build/css/custom.min.css" rel="stylesheet">
    <script src="~/ckeditor/ckeditor.js"></script>
    <link href="~/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
     <link href="~/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
     <link href="~/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
     <link href="~/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
     <link href="~/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
    

BuildingManager.Web/Views/Shared/_TopNavigation.cshtml
 <div class="top_nav">
          <div class="nav_menu">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                  <li class="nav-item">
                    @if (!User.Identity.IsAuthenticated)
                    {
                      <a asp-controller="Auth" asp-action="Login">Login</a>
                    }
                    else
                    {
                      <a asp-controller="Auth" asp-action="Logout">Logout</a>
                    }
                     @if (User.IsInRole("Admin"))
                     {
                       <li class="nav-item mr-3 ml-3">
                          <a asp-controller="Announcement" asp-action="Index">Yönetim Paneli</a>
                       </li>
                     }
                  </li>
                </ul>
            </nav>
          </div>
        </div>

BuildingManager.Web/Views/Shared/_UserSideBar.cshtml
   <div class="navbar nav_title" style="border: 0;">
                <a href="#" class="site_title"><span>Building Manager</span></a>
              </div>
  
              <div class="clearfix"></div>
  
              <!-- menu profile quick info -->
   <div class="profile clearfix">
     <div class="profile_pic">
       <img src="~/images/img.jpg" alt="..." class="img-circle profile_img">
     </div>
     <div class="profile_info">
       @if (User.Identity.IsAuthenticated)
       {
         <span>Hoşgeldiniz</span>
         <h2>@User.Identity.Name</h2>
       }
     </div>
   </div>
              <!-- /menu profile quick info -->
   <br />
  
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <ul class="nav side-menu">
              <li><a asp-controller="Home" asp-action="Index"><i class="fa fa-bullhorn"></i>Duyurular</a></li>
              <li><a><i class="fa fa-building"></i> Site <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a asp-controller="Home" asp-action="GetBuildings"><i class="fa fa-building"></i>Bloklar</a></li>
                      <li><a asp-controller="Home" asp-action="GetFlats"><i class="fa fa-home"></i>Daireler</a></li>
                    </ul>
              </li>
           <li><a><i class="fa fa-envelope"></i> Mesajlar <span class="fa fa-chevron-down"></span></a>
           <ul class="nav child_menu">
             <li><a asp-controller="Home" asp-action="Inbox"><i class="fa fa-inbox"></i>Gelen Kutusu</a></li>
             <li><a asp-controller="Home" asp-action="Outbox"><i class="fa fa-arrow-right"></i>Giden Kutusu</a></li>
             <li><a asp-controller="Home" asp-action="SendMessage"><i class="fa fa-comments"></i>Mesaj Gönder</a></li>
           </ul>
           <li><a><i class="fa fa-cc-visa"></i> Finans <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                       <li><a asp-controller="Home" asp-action="GetExpenseTypes"><i class="fa fa-shopping-cart"></i>Gider Tipleri</a></li>
                       <li><a asp-controller="Home" asp-action="GetNonPaidExpense"><i class="fa fa-money"></i>Giderler</a></li>
                    </ul>
                   </li>
                  </ul> 
        </div>

  </div>