BuildingManager.Web/Controllers/BuildingController.cs
using System.Threading.Tasks;
using BuildingManager.Business.Abstract;
using BuildingManager.Business.Dtos;
using BuildingManager.Web.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace BuildingManager.Web.Controllers
{
    [AuthorizeByRole(Roles="Admin")]
    public class BuildingController : Controller
    {
        private IBuildingService _buildingService;

        public BuildingController(IBuildingService buildingService)
        {
            _buildingService = buildingService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var buildings = await _buildingService.GetAllAsync();
            return View(buildings.Data);
        }

        [HttpGet]
        public IActionResult AddBuilding()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBuilding(BuildingDto buildingDto)
        {
            if (!ModelState.IsValid)
            {
                return View(buildingDto);
            }
            await _buildingService.AddAsync(buildingDto);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult DeleteBuilding(int id)
        {
            _buildingService.Remove(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateBuilding(int id)
        {
            var building = await _buildingService.GetByIdAsync(id);
            if (building.Data == null)
            {
                return RedirectToAction("Index");
            }
            return View(building.Data);
        }
        
        [HttpPost]
        public IActionResult UpdateBuilding(BuildingDto buildingDto)
        {
            if (!ModelState.IsValid)
            {
                return View(buildingDto);
            }
            _buildingService.Update(buildingDto);
            return RedirectToAction("Index");
        }
        
    }
}

BuildingManager.Web/Views/Building/AddBuilding.cshtml
@model BuildingDto
<form asp-controller="Building" asp-action="AddBuilding" class="was-validated">
    <div class="mb-3">
        <label asp-for="BuildingName" class="form-label">Blok Adı</label>
        <input type="text" class="form-control" asp-for="BuildingName" required="" maxlength="1">
        <span asp-validation-for="BuildingName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="TotalFlat" class="form-label">Toplam Kat Sayısı</label>
        <input type="number" class="form-control" asp-for="TotalFlat" required="">
          <span asp-validation-for="TotalFlat" class="text-danger"></span>
        </div>
    <button type="submit" class="btn btn-primary">Ekle</button>
</form>

BuildingManager.Web/Views/Building/Index.cshtml
@model List<BuildingDto>

<div class="container mb-5 mt-5">
    <h3>Yeni Blok Ekle</h3>
    <a class="btn btn-success btn-sm" asp-controller="Building" asp-action="AddBuilding">
        Blok Ekle
    </a>
</div>

<table id="datatable" class="table table-striped table-bordered" style="width:100%" >
    <thead class="thead-info">
    <tr>
        <th>Id</th>
        <th>Blok İsmi</th>
        <th>Kat Sayısı</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var building in Model)
    {
        <tr>
            <td>@building.Id</td>
            <td>@building.BuildingName</td>
            <td>@building.TotalFlat</td>
            <td>
                <a class="btn btn-primary btn-sm" asp-controller="Building" asp-action="UpdateBuilding" 
                   asp-route-id="@building.Id">
                    Güncelle
                </a>
            </td>
            <td>
                <a class="btn btn-danger btn-sm" asp-controller="Building" asp-action="DeleteBuilding" 
                   asp-route-id="@building.Id">
                    Sil
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

BuildingManager.Web/Views/Building/UpdateBuilding.cshtml
@model BuildingDto
<form asp-controller="Building" asp-action="UpdateBuilding" class="was-validated">
    <div class="mb-3">
        <label asp-for="BuildingName" class="form-label">Blok Adı</label>
        <input type="text" class="form-control" asp-for="BuildingName" required="" maxlength="1">
        <span asp-validation-for="BuildingName" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="TotalFlat" class="form-label">Toplam Kat Sayısı</label>
        <input type="text" class="form-control" asp-for="TotalFlat" required="">
        <span asp-validation-for="TotalFlat" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="Id"/>
    <button type="submit" class="btn btn-primary">Ekle</button>
</form>