BuildingManager.Web/Controllers/AnnouncementController.cs
using System.Threading.Tasks;
using BuildingManager.Business.Abstract;
using BuildingManager.Business.Dtos;
using BuildingManager.Web.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace BuildingManager.Web.Controllers
{
    [AuthorizeByRole(Roles="Admin")]
    public class AnnouncementController : Controller
    {
        private IAnnouncementService _announcementService;

        public AnnouncementController(IAnnouncementService announcementService)
        {
            _announcementService = announcementService;
        }
        
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var announcements = await _announcementService.GetAllAsync();
            return View(announcements.Data);
        }
        
        [HttpGet]
        public IActionResult AddAnnouncement()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddAnnouncement(AnnouncementDto announcementDto)
        {
            if (!ModelState.IsValid)
            {
                return View(announcementDto);
            }
            await _announcementService.AddAsync(announcementDto);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public  IActionResult DeleteAnnouncement(int id)
        {
            _announcementService.Remove(id);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public async Task<IActionResult> UpdateAnnouncement(int id)
        {
            var announcement = await _announcementService.GetByIdAsync(id);
            if (announcement.Data == null)
            {
                return RedirectToAction("Index");
            }
            return View(announcement.Data);
        }
        
        [HttpPost]
        public IActionResult UpdateAnnouncement(AnnouncementDto announcement)
        {
            if (!ModelState.IsValid)
            {
                return View(announcement);
            }
            _announcementService.Update(announcement);
            return RedirectToAction("Index");
        }
        
        
    }
}

BuildingManager.Web/Views/Announcement/AddAnnouncement.cshtml
@model AnnouncementDto
<form asp-controller="Announcement" asp-action="AddAnnouncement">
    <div class="mb-3">
        <label asp-for="AnnouncementText">Duyuru</label>
        <textarea asp-for="AnnouncementText" ></textarea>
        <span asp-validation-for="AnnouncementText" class="text-danger"></span>
        <script type="text/javascript">CKEDITOR.replace('AnnouncementText');</script>
    </div>
    <button type="submit" class="btn btn-primary">Ekle</button>
</form>

BuildingManager.Web/Views/Announcement/Index.cshtml
@model IEnumerable<AnnouncementDto>

<div class="container mb-5 mt-5">
    <h3>Yeni Duyuru Ekle</h3>
    <a class="btn btn-success btn-sm" asp-controller="Announcement" asp-action="AddAnnouncement">
        Duyuru Ekle
    </a>
</div>

<table id="datatable" class="table table-striped table-bordered" style="width:100%" >
    <thead class="thead-info">
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Duyuru</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var announcement in Model)
    {
        <tr>
            <td>@announcement.Id</td>
            <td>@Html.Raw(announcement.AnnouncementText)</td>
            <td>
                <a class="btn btn-primary btn-sm" asp-controller="Announcement" asp-action="UpdateAnnouncement" 
                   asp-route-id="@announcement.Id">
                    Güncelle
                </a>
            </td>
            <td>
                <a class="btn btn-danger btn-sm" asp-controller="Announcement" asp-action="DeleteAnnouncement" 
                   asp-route-id="@announcement.Id">
                    Sil
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

BuildingManager.Web/Views/Announcement/UpdateAnnouncement.cshtml
@model AnnouncementDto
<form asp-controller="Announcement" asp-action="UpdateAnnouncement">
    <div class="mb-3">
        <label asp-for="AnnouncementText">Duyuru</label>
        <textarea asp-for="AnnouncementText" ></textarea>
        <span asp-validation-for="AnnouncementText" class="text-danger"></span>
        <script type="text/javascript">CKEDITOR.replace('AnnouncementText');</script>
    </div>
    <input type="hidden" asp-for="Id"/>
    <button type="submit" class="btn btn-primary">Güncelle</button>
</form>